### ISSUE TITLE
Wallet - multiple clients 

### ISSUE THREAD

**Issue by oppsig** [effectsToCause/verium-oldrepo#1]
If I connect multiple miners to my wallet over rpc and mine. Do I need to specify - - coinbase-addr or will it automatically be credited to my wallet? Every client seams to be mining. But veriumd getmininginfo shows 0 hash. But hash can be seen on every client.

**Comment by effectsToCause** [comment]
wallet only shows local hash but if miner does not show error when mining to wallet then it is working.
